name: app_manager
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: ^1.0.2
  # Flutter 的一些动画
  flutter_spinkit: "^4.1.2"
  shortcut: ^0.0.1
  path: ^1.8.0
  get: ^4.1.3
  global_repository:
    path: /Users/nightmare/Desktop/nightmare-space/global_repository
  flutter_svg: ^0.22.0
  share_plus: ^2.1.4
  hive: ^2.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
